@startuml

class Generalization {
public void get(Object oId)
public void put(Object oName)
}

class Base {
abstract public void get(Object oId);
abstract public void put(Object oName);
}

Base <|-- Generalization

@enduml