@startuml

class Context{
State State;
state getState()
}

abstract class State{
operation1();
operation2();
}

class ConcreteStateA extends State{
}

class ConcreteStateB extends State{
}

Context o-- State


@enduml